[build]
# Only trigger deployments when these patterns match changed files
# Uses gitignore-style patterns - JSON data files are excluded
watchPatterns = [
  "**/*.js",
  "package.json",
  "package-lock.json",
  "railway.toml"
]

[deploy]
restartPolicyType = "ON_FAILURE"
