[build]
# Only watch these paths for changes - excludes JSON data files
watchPaths = [
  "**/*.js",
  "package.json",
  "package-lock.json",
  "railway.toml",
  ".env"
]

[deploy]
restartPolicyType = "ON_FAILURE"
