[build]
# Ignore JSON data files - they're runtime data, not code
watchPaths = ["**/*.js", "package.json", "package-lock.json"]

[build.watchIgnore]
paths = ["reminders.json", "faq.json", "schedule.json"]
